### PR TITLE
Fix negatives

### PR DESCRIPTION
**Pull request by smcabrera**
I fixed the way that negatives behave in mathematical operations. I also added unit tests for each of the mathematical operations to test working properly with negatives. 

I toyed with changing total to be stored as a negative number (total: -5) but I decided that you probably have a good reason for using the negative boolean for tracking whether or not the duration is negative so the only changes I made were in the mathematical operations. It's not that DRY, but I wanted to send you a first run and see what you thought.

I only changed the ruby version so that I could test on my machine. That should be in a separate commit which you can remove.

### CODE REVIEW

**Comment by AugustoGu** [comment]
:+1: 
Good Job. This project seems to be stopped.
:(

**Comment by peleteiro** [comment]
It kinda did. Do you want to take over the project?

**Comment by AugustoGu** [comment]
I think that @smcabrera is the ideal person for this.   :D

**Comment by smcabrera** [comment]
@peleteiro @AugustoGu I'd be happy to :-)

**Comment by peleteiro** [comment]
@smcabrera Which email address do you use for rubygems.org?

**Comment by smcabrera** [comment]
stephen.m.cabrera@gmail.com

**Comment by peleteiro** [comment]
@smcabrera Added you as owner on rubygem.org using stephen.m.cabrera@gmail.com.

Good luck with ruby-duration and fell free to make any change you want to. ;) thanks

**Pull request merged**
